version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: "increase-if-necessary"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 14
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 14
    groups:
      github-actions:
        patterns:
          - "*"
